version: "3"

services:
  lp-app:
    build:
      context: .
    ports:
      - "5555:5000"
    depends_on:
      - mongo
    networks:
      - app-network
    command: ./wait-for.sh mongo:27017 -- npm run heroku-start

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge 