version: "3"

services:
  lp-app:
    build:
      context: .
    ports:
      - "5555:5000"
    depends_on:
      - mongo
      - postgres
    networks:
      - app-network
    command: ./wait-for.sh mongo:27017 -- npm run heroku-start
    restart: always

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER_NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - lp-mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
    restart: always

  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - '5436:5432'
    volumes:
      - lp-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    networks:
      - app-network
    restart: always

networks:
    app-network:
        driver: bridge 

volumes:
  lp-postgres:
    driver: local
  lp-mongo:
    driver: local