# TODO: если хватит времени автоматизировать в LP-130 
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ LP-130 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      # exec $SHELL -l
      - name: Run a one-line script
        run: | 
          curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -i /opt/yandex-cloud -n
          /opt/yandex-cloud/bin/yc config set token AQAAAAAUJVQSAATuwdeTvXDhnk9Tv0wcU5bC4vE
          /opt/yandex-cloud/bin/yc config profile create batia
          /opt/yandex-cloud/bin/yc config set folder-id b1gb6olmron2khu1fqf4
          /opt/yandex-cloud/bin/yc config set cloud-id b1g1k4hfma98vqpph1mh
          docker build -t cr.yandex/crpasb6c8g98nppq2f2v/lp-app:vTEST .
          docker push cr.yandex/crpasb6c8g98nppq2f2v/lp-app:vTEST

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "her"
